import { env } from './config/env';

export enum Event_Types {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  CHAT_INITIATED = 'CHAT_INITIATED',
  CHAT_REJECTED = 'CHAT_REJECTED',
  CALL_CANCELLED = 'CALL_CANCELLED',
  CHAT_STARTED = 'CHAT_STARTED',
  CHAT_ENDED = 'CHAT_ENDED',
  CALL_INITIATED = 'CALL_INITIATED',
  CALL_STARTED = 'CALL_STARTED',

  CALL_ENDED = 'CALL_ENDED',
  CALL_REJECTED = 'CALL_REJECTED',
  USER_CREATED = 'USER_CREATED',
  WALLET_BALENCE_ERROR = 'WALLET_BALENCE_ERROR',
  PROFESSIONAL_LOGIN = 'PROFESSIONAL_LOGIN',

  // Admin Events
  ADMIN_LOGIN = 'ADMIN_LOGIN',
  ADMIN_USER_STATUS_CHANGED = 'ADMIN_USER_STATUS_CHANGED',
  ADMIN_PROFESSIONAL_STATUS_CHANGED = 'ADMIN_PROFESSIONAL_STATUS_CHANGED',
  ADMIN_WALLET_UPDATED = 'ADMIN_WALLET_UPDATED',
  ADMIN_PROFESSIONAL_VERIFIED = 'ADMIN_PROFESSIONAL_VERIFIED',
  ADMIN_RATES_UPDATED = 'ADMIN_RATES_UPDATED',
}
export enum RedisChannelsSubScriber {
  DATAPARSER = 'DataSender',
}
export enum RedisChannelsPublisher {
  PENDING_TASK = 'pending_task',
}

export const commissionRate = 0.2;
export const WSURL = env.WS_URL;
